#!/usr/bin/env ruby

#---------
#  paths
#---------

require 'pathname'

def realpath(path)
  Pathname.new(__FILE__).dirname.realpath.join(path)
end

BUILD_DIR = realpath('../build')
THEIR_DIR = realpath('../their-stuff')
NOJS_DIR = realpath('nojs')
PONG_DIR = realpath('js/pong')


#--------------
#  main tasks
#--------------

desc 'build production version'
task :build do
  dir
  html
  css
  js
end

desc 'build development version'
task :dev do
  dir
  html_dev
  js_dev
end


#------------
#  subtasks
#------------

desc 'render and compress css'
task :css do
  output = "#{BUILD_DIR}/style.css"
  system "cp #{THEIR_DIR}/reset/reset.css #{output}"
  system "sass #{NOJS_DIR}/production.sass >> #{output}"
  system "java -jar #{THEIR_DIR}/yuicompressor/build/yuicompressor-2.4.2.jar "+
         "-o #{output} #{output}"
end

desc 'prepare empty build directory'
task :dir do
  system "[ ! -d #{BUILD_DIR} ] && mkdir #{BUILD_DIR}"
  system "rm -rf #{BUILD_DIR}/*"
end

desc 'render html'
task :html do
  system "haml #{NOJS_DIR}/production.haml > #{BUILD_DIR}/index.html"
end

desc 'render development html'
task :html_dev do
  system "haml #{NOJS_DIR}/development.haml > #{BUILD_DIR}/index.html"
end

desc 'compress js'
task :js do
  system "java -jar #{THEIR_DIR}/compiler/compiler.jar " +
         "--compilation_level=SIMPLE_OPTIMIZATIONS " +
         "--js=#{PONG_DIR}/0-init.js " +
         "--js=#{PONG_DIR}/1-border.js " +
         "--js=#{PONG_DIR}/1-controlsscreen.js " +
         "--js=#{PONG_DIR}/1-keys.js " +
         "--js=#{PONG_DIR}/1-racket.js " +
         "--js=#{PONG_DIR}/1-shuttlecock.js " +
         "--js=#{PONG_DIR}/1-transition.js " +
         "--js=#{PONG_DIR}/2-pause.js " +
         "--js=#{PONG_DIR}/3-play.js " +
         "--js_output_file=#{BUILD_DIR}/pong.js"
end

desc 'symlink js files to build dir'
task :js_dev do
  system "cp #{THEIR_DIR}/jquery/jquery.min.js #{BUILD_DIR}"
  system "ln -s #{PONG_DIR}/*.js #{BUILD_DIR}"
end
