#!/usr/bin/env ruby

#---------
#  paths
#---------

require 'pathname'

def realpath(path)
  Pathname.new(__FILE__).dirname.realpath.join(path)
end

BUILD_DIR = realpath('build')
THEIR_CODE_DIR = realpath('their-code')
MY_CODE_DIR = realpath('my-code')
NOJS_DIR = MY_CODE_DIR.join('nojs')
PONG_DIR = MY_CODE_DIR.join('js/pong')


#--------------
#  main tasks
#--------------

desc 'build production version'
task :build do
  dir
  html
  js
end

desc 'build development version'
task :dev do
  dir
  html_dev
  js_dev
end


#------------
#  subtasks
#------------

desc 'prepare empty build directory'
task :dir do
  system "[ ! -d #{BUILD_DIR} ] && mkdir #{BUILD_DIR}"
  system "rm -rf #{BUILD_DIR}/*"
end

desc 'render html'
task :html do
  system "haml #{NOJS_DIR}/production.haml > #{BUILD_DIR}/index.html"
end

desc 'render development html'
task :html_dev do
  system "haml #{NOJS_DIR}/development.haml > #{BUILD_DIR}/index.html"
end

desc 'copy jQuery'
task :jQuery do
  system "cp #{THEIR_CODE_DIR}/jquery/jquery.min.js #{BUILD_DIR}"
end

desc 'compress js'
task :js do
  jQuery
  system "java -jar #{THEIR_CODE_DIR}/compiler/compiler.jar " +
         "--compilation_level=SIMPLE_OPTIMIZATIONS " +
         "--js=#{PONG_DIR}/init.js " +
         "--js=#{PONG_DIR}/ball.js " +
         "--js=#{PONG_DIR}/keys.js " +
         "--js=#{PONG_DIR}/pause.js " +
         "--js=#{PONG_DIR}/racket.js " +
         "--js=#{PONG_DIR}/play.js " +
         "--js_output_file=#{BUILD_DIR}/pong.js"
end

desc 'symlink js files to build dir'
task :js_dev do
  jQuery
  system "ln -s #{PONG_DIR}/*.js #{BUILD_DIR}"
end
