#!/usr/bin/env ruby

require 'pathname'


def realpath(path)
  Pathname.new(__FILE__).dirname.realpath.join(path)
end


SOURCE_DIR = realpath('src')
BUILD_DIR = realpath('build')


desc 'build all'
task :build do
  dir
  html
  js
end


desc 'build without compressing js'
task :dev do
  dir
  html
  system "ln -s #{SOURCE_DIR}/pong.js #{BUILD_DIR}"
end


desc 'prepare empty build directory'
task :dir do
  system "[ ! -d #{BUILD_DIR} ] && mkdir #{BUILD_DIR}"
  system "rm -rf #{BUILD_DIR}/*"
end


desc 'render html'
task :html do
  system "haml #{SOURCE_DIR}/pong.haml > #{BUILD_DIR}/index.html"
end


desc 'compress js'
task :js do
  system "cp #{SOURCE_DIR}/jquery.min.js #{BUILD_DIR}"
  system "java -jar #{SOURCE_DIR}/compiler/compiler.jar " +
         "--compilation_level=SIMPLE_OPTIMIZATIONS " +
         "--js=#{SOURCE_DIR}/pong.js " +
         "--js_output_file=#{BUILD_DIR}/pong.js"
end
